[jabley] fix node puppet usage
Was unable to install npm modules.

```
Error: /Stage[main]/People::Jabley/Npm_module[gulp]: Could not evaluate: 757: unexpected token at 'opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log/destinations.rb:94:in `flush': Bad file descriptor (Errno::EBADF)
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log/destinations.rb:94:in `handle'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:170:in `block in newmessage'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:169:in `each'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:169:in `newmessage'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:266:in `initialize'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:84:in `new'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:84:in `create'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/logging.rb:8:in `send_log'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/logging.rb:15:in `block (2 levels) in <module:Logging>'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/logging.rb:27:in `log_exception'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:272:in `rescue in block in execute_posix'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:246:in `block in execute_posix'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:297:in `call'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:297:in `block in safe_posix_fork'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:290:in `fork'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:290:in `safe_posix_fork'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:237:in `execute_posix'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:182:in `execute'
	from /opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/provider.rb:120:in `execute'
	from /opt/boxen/repo/shared/nodejs/lib/puppet/provider/npm_module/npm.rb:164:in `npmlist'
```

```
/opt/nodes/0.10/bin/npm list --global --json --depth=0 --silent
```

Was failing due to `/opt/nodes/0.10` linking to the recently removed
`/opt/nodes/0.10.36`.

Adding these back in seems to have fixed it.